/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ReclamacionesRouteImport } from './routes/reclamaciones'
import { Route as AuthenticatedCategoriaRouteImport } from './routes/_authenticated.categoria'
import { Route as AuthenticatedLegalFirmarRouteImport } from './routes/_authenticated.legal.firmar'
import { Route as AuthenticatedPacienteEsperaRouteImport } from './routes/_authenticated.paciente.espera'
import { Route as AuthenticatedPacientePaquetesRouteImport } from './routes/_authenticated.paciente.paquetes'
import { Route as AuthenticatedPacientePagarPagoIdRouteImport } from './routes/_authenticated.paciente.pagar.$pagoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclamacionesRoute = ReclamacionesRouteImport.update({
  id: '/reclamaciones',
  path: '/reclamaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCategoriaRoute = AuthenticatedCategoriaRouteImport.update({
  id: '/categoria',
  path: '/categoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLegalFirmarRoute =
  AuthenticatedLegalFirmarRouteImport.update({
    id: '/legal/firmar',
    path: '/legal/firmar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacienteEsperaRoute =
  AuthenticatedPacienteEsperaRouteImport.update({
    id: '/paciente/espera',
    path: '/paciente/espera',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacientePaquetesRoute =
  AuthenticatedPacientePaquetesRouteImport.update({
    id: '/paciente/paquetes',
    path: '/paciente/paquetes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacientePagarPagoIdRoute =
  AuthenticatedPacientePagarPagoIdRouteImport.update({
    id: '/paciente/pagar/$pagoId',
    path: '/paciente/pagar/$pagoId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/categoria': typeof AuthenticatedCategoriaRoute
  '/legal/firmar': typeof AuthenticatedLegalFirmarRoute
  '/paciente/espera': typeof AuthenticatedPacienteEsperaRoute
  '/paciente/paquetes': typeof AuthenticatedPacientePaquetesRoute
  '/paciente/pagar/$pagoId': typeof AuthenticatedPacientePagarPagoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/categoria': typeof AuthenticatedCategoriaRoute
  '/legal/firmar': typeof AuthenticatedLegalFirmarRoute
  '/paciente/espera': typeof AuthenticatedPacienteEsperaRoute
  '/paciente/paquetes': typeof AuthenticatedPacientePaquetesRoute
  '/paciente/pagar/$pagoId': typeof AuthenticatedPacientePagarPagoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/_authenticated/categoria': typeof AuthenticatedCategoriaRoute
  '/_authenticated/legal/firmar': typeof AuthenticatedLegalFirmarRoute
  '/_authenticated/paciente/espera': typeof AuthenticatedPacienteEsperaRoute
  '/_authenticated/paciente/paquetes': typeof AuthenticatedPacientePaquetesRoute
  '/_authenticated/paciente/pagar/$pagoId': typeof AuthenticatedPacientePagarPagoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/legal'
    | '/reclamaciones'
    | '/categoria'
    | '/legal/firmar'
    | '/paciente/espera'
    | '/paciente/paquetes'
    | '/paciente/pagar/$pagoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/legal'
    | '/reclamaciones'
    | '/categoria'
    | '/legal/firmar'
    | '/paciente/espera'
    | '/paciente/paquetes'
    | '/paciente/pagar/$pagoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/legal'
    | '/reclamaciones'
    | '/_authenticated/categoria'
    | '/_authenticated/legal/firmar'
    | '/_authenticated/paciente/espera'
    | '/_authenticated/paciente/paquetes'
    | '/_authenticated/paciente/pagar/$pagoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalRoute: typeof LegalRoute
  ReclamacionesRoute: typeof ReclamacionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclamaciones': {
      id: '/reclamaciones'
      path: '/reclamaciones'
      fullPath: '/reclamaciones'
      preLoaderRoute: typeof ReclamacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/categoria': {
      id: '/_authenticated/categoria'
      path: '/categoria'
      fullPath: '/categoria'
      preLoaderRoute: typeof AuthenticatedCategoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/legal/firmar': {
      id: '/_authenticated/legal/firmar'
      path: '/legal/firmar'
      fullPath: '/legal/firmar'
      preLoaderRoute: typeof AuthenticatedLegalFirmarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paciente/espera': {
      id: '/_authenticated/paciente/espera'
      path: '/paciente/espera'
      fullPath: '/paciente/espera'
      preLoaderRoute: typeof AuthenticatedPacienteEsperaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paciente/paquetes': {
      id: '/_authenticated/paciente/paquetes'
      path: '/paciente/paquetes'
      fullPath: '/paciente/paquetes'
      preLoaderRoute: typeof AuthenticatedPacientePaquetesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paciente/pagar/$pagoId': {
      id: '/_authenticated/paciente/pagar/$pagoId'
      path: '/paciente/pagar/$pagoId'
      fullPath: '/paciente/pagar/$pagoId'
      preLoaderRoute: typeof AuthenticatedPacientePagarPagoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriaRoute: typeof AuthenticatedCategoriaRoute
  AuthenticatedLegalFirmarRoute: typeof AuthenticatedLegalFirmarRoute
  AuthenticatedPacienteEsperaRoute: typeof AuthenticatedPacienteEsperaRoute
  AuthenticatedPacientePaquetesRoute: typeof AuthenticatedPacientePaquetesRoute
  AuthenticatedPacientePagarPagoIdRoute: typeof AuthenticatedPacientePagarPagoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriaRoute: AuthenticatedCategoriaRoute,
  AuthenticatedLegalFirmarRoute: AuthenticatedLegalFirmarRoute,
  AuthenticatedPacienteEsperaRoute: AuthenticatedPacienteEsperaRoute,
  AuthenticatedPacientePaquetesRoute: AuthenticatedPacientePaquetesRoute,
  AuthenticatedPacientePagarPagoIdRoute: AuthenticatedPacientePagarPagoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalRoute: LegalRoute,
  ReclamacionesRoute: ReclamacionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
